import { expect, it, describe } from 'vitest'
import { getLastMoment } from './1503. Last Moment Before All Ants Fall Out of a Plank'

// Generated by CodiumAI

describe('getLastMoment', () => {

    // Returns the correct position when there is only one ant on the left side
    it('should return the correct position when there is only one ant on the left side', () => {
      const n = 5;
      const left = [2];
      const right = [];
      const result = getLastMoment(n, left, right);
      expect(result).toBe(2);
    });

    // Returns the correct position when there is only one ant on the right side
    it('should return the correct position when there is only one ant on the right side', () => {
      const n = 5;
      const left = [];
      const right = [3];
      const result = getLastMoment(n, left, right);
      expect(result).toBe(2);
    });

    // Returns the correct position when there are ants on both sides

    // Returns the correct position when all ants are at the leftmost position
    it('should return the correct position when all ants are at the leftmost position', () => {
      const n = 5;
      const left = [0, 0, 0];
      const right = [1, 2, 3];
      const result = getLastMoment(n, left, right);
      expect(result).toBe(4);
    });
});
