// Generated by CodiumAI
import { expect, it, describe } from 'vitest'
import { twoSum } from './1. Two Sum'
describe('twoSum', () => {

    // Returns an array with two indices that sum up to the target
    it('should return an array with two indices that sum up to the target', () => {
        const nums = [2, 7, 11, 15];
        const target = 9;
        const result = twoSum(nums, target);
        expect(result).toEqual([0, 1]);
    });

    // Works with positive and negative integers
    it('should work with positive and negative integers', () => {
        const nums = [-2, 7, -11, 15];
        const target = 5;
        const result = twoSum(nums, target);
        expect(result).toEqual([0, 1]);
    });

    // Works with duplicate integers in the input array
    it('should work with duplicate integers in the input array', () => {
        const nums = [2, 7, 11, 15, 2];
        const target = 4;
        const result = twoSum(nums, target);
        expect(result).toEqual([0, 4]);
    });
});
